### PR TITLE
Addition to DS logging

### PR DESCRIPTION
**Pull request by ky28059**
@rishay-jain

### CODE REVIEW

**Review by ky28059 — COMMENTED** [review]
Is the idea to construct these packets in various subsystems depending on what is getting logged? How are these packets actually being logged? They seem to just be wrappers around strings at the moment.

**Comment by rishay-jain** [comment]
they are wrappers around strings– whatever is printed out ends up in the driver station logs as well, so really its just a way of formatting printlns so they are more readable in the event list. it will also be able to automatically add in other pieces of information, such as position, heading, etc., so we get more context when reviewing logs.

**Comment by ky28059** [comment]
So is it the responsibility of each subsystem to call `System.out.println(message.display())` or will there be some sort of manager structure? If it's the former, maybe this would be better as static methods on a util class like `LoggingUtil.logStateChange(...)` instead of having to construct a wrapper object just to call a formatting method and discard it.

**Comment by ky28059** [comment]
ie. is the current plan to log a message from a subsystem
```java
StateChangePacket message = new StateChangePacket("...", "...", ..., ...);
System.out.println(message.display());
```
?

**Comment by e3l** [comment]
https://www.chiefdelphi.com/t/improbable-java-slow-down-in-combining-doubles-and-strings/350331

**Comment by ky28059** [comment]
I'd probably benchmark that to see if we're really having the same problem as them, because that thread is 4 years old and seems to be a Java 11 issue.

**Pull request closed without merging**
