### PR TITLE
Abstract `GoAndPlaceCommand` for teleop

### PR DESCRIPTION
**Pull request by ky28059**
Supersedes #41.

### CODE REVIEW

**Comment by e3l** [comment]
what do you all think abt using shuffleboard as the UI for these commands for now, maybe we can make tiny buttons that line up next to & corresponding to the Field2D

**Comment by e3l** [comment]
can be updated to use DropCommand

**Comment by ky28059** [comment]
Waiting on #46 and #51 before rebase and merge.

**Comment by e3l** [comment]
too outdated to rebase or merge as-is

**Pull request closed without merging**
